# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82f3ec5d5c0e9fa9ee439dc6c733addf20eb6331273707b584c7fa1bc44c7d1987abc3bfe7a6806b539d2f9531ceb484931e960700836aba1275b09f561cab6d

test:
  secret_key_base: 4e7cf6429a53daec9b4edbafad983fe78b88fa42e7ff035cf9b3e525741d5daac38c43596b0e9d8abb2ddf96453daa80f5e7ef1d5e7c4caf44854a4fc7ce7a64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
